image: artifactory.wma.chs.usgs.gov/docker-official-mirror/rocker/geospatial:latest

variables:
  _R_CHECK_CRAN_INCOMING_: "false"
  _R_CHECK_FORCE_SUGGESTS_: "true"
  _R_CHECK_DONTTEST_EXAMPLES_: "false"
  NOT_CRAN: "true"
  R_REMOTES_NO_ERRORS_FROM_WARNINGS: "false"
  R_PROFILE: "$R_HOME/etc/Rprofile.site"
  R_LIBS_USER: "$CI_PROJECT_DIR/ci/lib"
  R_LIBS: "$CI_PROJECT_DIR/ci/lib"
  CRAN: "https://packagemanager.rstudio.com/cran/latest"

cache:
  paths:
    - $R_LIBS_USER

before_script:
  - mkdir -p $R_LIBS_USER
  - echo "options(Ncpus=$(nproc --all), repos=c(CRAN='$CRAN'))" >> $R_PROFILE
  - Rscript -e "remotes::install_deps(dependencies=TRUE)"

test:
  stage: test
  script:
    - Rscript -e "rcmdcheck::rcmdcheck(args=c('--no-manual', '--no-examples', '--no-tests'), build_args=c('--no-manual', '--no-resave-data'), check_dir='.', error_on='warning')"
    - Rscript -e "x <- covr::package_coverage(type='all'); covr::report(x, file='coverage.html', browse=FALSE); x"
  artifacts:
    paths:
      - "*.Rcheck"
      - "coverage.html"
      - "lib"
  coverage: '/Coverage: \d+.\d+\%/'
